### ISSUE TITLE
ERStat_WRT_2018_G(18392)_20190726.txt

### ISSUE THREAD

**Issue by rootsmusic** [openelections/openelections-sources-pa#10]
What's in [ERStat_WRT_2018_G(18392)_20190726.txt](https://github.com/openelections/openelections-sources-pa/blob/master/2018/ERStat_WRT_2018_G(18392)_20190726.txt)?  Was it a subset of [ERStat_2018_G(114234)_20190726.txt](https://github.com/openelections/openelections-sources-pa/blob/master/2018/ERStat_2018_G(114234)_20190726.txt)?  Thanks.

**Comment by dwillis** [comment]
@rootsmusic The WRT file is write-ins.
