### ISSUE TITLE
ERStat_2018_G(114234)_20190726.txt vs. https://electionreturns.pa.gov

### ISSUE THREAD

**Issue by rootsmusic** [openelections/openelections-sources-pa#11]
Why did [ERStat_2018_G(114234)_20190726.txt](https://github.com/openelections/openelections-sources-pa/blob/master/2018/ERStat_2018_G(114234)_20190726.txt) differ from the [website's official results](https://electionreturns.pa.gov/General/SummaryResults?ElectionID=63&ElectionType=G&IsActive=0)?  The differences were in [Allegheny](https://github.com/openelections/openelections-sources-pa/blob/master/2018/general/Allegheny%20PA%202018%20General%20Official.xls), [Westmoreland](https://github.com/openelections/openelections-sources-pa/blob/master/2018/general/Westmoreland%20PA%202018-General-PrecinctSummary.htm), and [York](https://github.com/openelections/openelections-sources-pa/blob/master/2018/general/York%20PA%202018GeneralDistrictRecap.pdf).  Below are the relevant candidates from ERStat_2018_G(114234)_20190726.txt, grouped by County Code with the last column from the website's official results.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

County Code | Candidate Number | Candidate Last Name | Candidate First Name | Candidate Middle Name | Candidate Suffix | Vote Total | Official Votes
-- | -- | -- | -- | -- | -- | -- | --
2 | 2018C1448 | LAMB | CONOR | JAMES |   | 145,903 | 146,310
2 | 2018C1384 | ROTHFUS | KEITH |   |   | 102,447 | 102,697
2 | 2018C1377 | DOYLE | MICHAEL | F | JR | 231,450 | 231,472
65 | 2018C0950 | CASEY | ROBERT | P | JR | 63,956 | 63,778
65 | 2018C0510 | BARLETTA | LOUIS | J. |   | 79,379 | 79,078
65 | 2018C1527 | GALE | NEAL | TAYLOR |   | 707 | 704
65 | 2018C1513 | KERNS | DALE | R | JR | 1,706 | 1,698
65 | 2018C1049 | WOLF | THOMAS | W |   | 68,146 | 67,950
65 | 2018C0493 | WAGNER | SCOTT | R |   | 76,413 | 76,126
65 | 2018C1528 | GLOVER | PAUL |   |   | 695 | 690
65 | 2018C1514 | KRAWCHUK | KENNETH | V |   | 1,532 | 1,529
65 | 2018C0977 | DOOLEY | CLARE | HELEN |   | 6,366 | 6,237
65 | 2018C0413 | REESE | MICHAEL | P |   | 14,991 | 14,632
67 | 2018C1427 | KING | JESSICA |   |   | 26,627 | 24,709
67 | 2018C1471 | SMUCKER | LLOYD | K |   | 49,883 | 49,920

</body>

</html>

**Comment by dwillis** [comment]
Because the [ERStat_2018_G(114234)_20190726.txt](https://github.com/openelections/openelections-sources-pa/blob/master/2018/ERStat_2018_G(114234)_20190726.txt) file is a snapshot and the other one got updated later. Bad, but true.

**Comment by rootsmusic** [comment]
Ok @dwillis, I'm validating [20181106__pa__general__precinct.csv](https://github.com/openelections/openelections-data-pa/blob/master/2018/20181106__pa__general__precinct.csv).  Unfortunately, precinct-level is unavailable from the[ state agency](https://electionreturns.pa.gov/General/SummaryResults?ElectionID=63&ElectionType=G&IsActive=0#).  Since ERStat_2018_G(114234)_20190726.txt was precinct-level, I was hoping to use it as the official results before finding the above table's discrepancies.  Was there another source of precinct-level results that matched the state's official results?  Thanks.

**Comment by dwillis** [comment]
@rootsmusic - no, unfortunately all we have is that state-generated file that we know has discrepancies and the files produced by each county (https://github.com/openelections/openelections-sources-pa/tree/master/2018/general). Probably the best we can do is to match county-level totals to rollups of individual county precinct results.
